CREATE TABLE [Absence].[DIM_SETID_TBL] (

	[SETID_ID] int NOT NULL, 
	[SETID] varchar(255) NOT NULL, 
	[DESCR] varchar(255) NOT NULL
);


GO
ALTER TABLE [Absence].[DIM_SETID_TBL] ADD CONSTRAINT PK_DIM_SETID_TBL primary key NONCLUSTERED ([SETID_ID]);