CREATE TABLE [Absence].[DIM_COUNTRY_TBL] (

	[COUNTRY_ID] int NOT NULL, 
	[COUNTRY] varchar(255) NOT NULL, 
	[DESCR] varchar(255) NOT NULL
);


GO
ALTER TABLE [Absence].[DIM_COUNTRY_TBL] ADD CONSTRAINT PK_DIM_COUNTRY_TBL primary key NONCLUSTERED ([COUNTRY_ID]);