CREATE TABLE [Absence].[DIM_MAR_STATUS_TBL] (

	[FIELDVALUE_ID] int NOT NULL, 
	[FIELDVALUE] varchar(255) NOT NULL, 
	[XLATLONGNAME] varchar(255) NULL
);


GO
ALTER TABLE [Absence].[DIM_MAR_STATUS_TBL] ADD CONSTRAINT PK_DIM_MAR_STATUS_TBL primary key NONCLUSTERED ([FIELDVALUE_ID], [FIELDVALUE]);