CREATE TABLE [Absence].[DIM_DEPT_TBL] (

	[DEPTID_ID] int NOT NULL, 
	[DEPTID] varchar(255) NOT NULL, 
	[SETID_ID] int NOT NULL, 
	[DESCR] varchar(255) NULL
);


GO
ALTER TABLE [Absence].[DIM_DEPT_TBL] ADD CONSTRAINT PK_DIM_DEPT_TBL primary key NONCLUSTERED ([DEPTID_ID]);
GO
ALTER TABLE [Absence].[DIM_DEPT_TBL] ADD CONSTRAINT FK_DIM_DEPT_TBL_DIM_SETID_TBL FOREIGN KEY ([SETID_ID]) REFERENCES [Absence].[DIM_SETID_TBL]([SETID_ID]);