CREATE TABLE [Absence].[DIM_JOB_TBL] (

	[EMPLID_ID] int NOT NULL, 
	[EMPL_RCD] int NOT NULL, 
	[DEPTID_ID] int NULL, 
	[LOCATION_ID] int NULL, 
	[HIRE_DT] date NULL, 
	[HOURLY_RT] float NULL
);


GO
ALTER TABLE [Absence].[DIM_JOB_TBL] ADD CONSTRAINT PK_DIM_JOB_TBL primary key NONCLUSTERED ([EMPLID_ID], [EMPL_RCD]);
GO
ALTER TABLE [Absence].[DIM_JOB_TBL] ADD CONSTRAINT FK_DIM_JOB_TBL_DIM_DEPT_TBL FOREIGN KEY ([DEPTID_ID]) REFERENCES [Absence].[DIM_DEPT_TBL]([DEPTID_ID]);
GO
ALTER TABLE [Absence].[DIM_JOB_TBL] ADD CONSTRAINT FK_DIM_JOB_TBL_DIM_LOCATION_TBL FOREIGN KEY ([LOCATION_ID]) REFERENCES [Absence].[DIM_LOCATION_TBL]([LOCATION_ID]);
GO
ALTER TABLE [Absence].[DIM_JOB_TBL] ADD CONSTRAINT FK_DIM_JOB_TBL_DIM_PERSONAL_TBL FOREIGN KEY ([EMPLID_ID]) REFERENCES [Absence].[DIM_PERSONAL_TBL]([EMPLID_ID]);