CREATE TABLE [Absence].[DIM_GP_STATUS_TBL] (

	[TRANSACTION_NBR] varchar(255) NOT NULL, 
	[EMPLID_ID] int NOT NULL, 
	[SUB_DATE] date NULL, 
	[APR_DATE] date NULL, 
	[STATUS_ID] int NULL
);


GO
ALTER TABLE [Absence].[DIM_GP_STATUS_TBL] ADD CONSTRAINT PK_DIM_GP_STATUS_TBL primary key NONCLUSTERED ([TRANSACTION_NBR]);