CREATE TABLE [Absence].[DIM_LOCATION_TBL] (

	[LOCATION_ID] int NOT NULL, 
	[LOCATION] varchar(255) NOT NULL, 
	[SETID_ID] int NOT NULL, 
	[COUNTRY_ID] int NULL, 
	[ADDRESS] varchar(255) NOT NULL
);


GO
ALTER TABLE [Absence].[DIM_LOCATION_TBL] ADD CONSTRAINT PK_DIM_LOCATION_TBL primary key NONCLUSTERED ([LOCATION_ID]);
GO
ALTER TABLE [Absence].[DIM_LOCATION_TBL] ADD CONSTRAINT FK_DIM_LOCATION_TBL_DIM_COUNTRY_TBL FOREIGN KEY ([COUNTRY_ID]) REFERENCES [Absence].[DIM_COUNTRY_TBL]([COUNTRY_ID]);
GO
ALTER TABLE [Absence].[DIM_LOCATION_TBL] ADD CONSTRAINT FK_DIM_LOCATION_TBL_DIM_SETID_TBL FOREIGN KEY ([SETID_ID]) REFERENCES [Absence].[DIM_SETID_TBL]([SETID_ID]);