CREATE TABLE [Absence].[FACT_ABSENCE_TBL] (

	[TRANSACTION_NBR] varchar(255) NOT NULL, 
	[EMPLID_ID] int NOT NULL, 
	[EMPL_RCD] varchar(255) NOT NULL, 
	[PIN_NUM] int NOT NULL, 
	[BGN_DT] date NOT NULL, 
	[END_DT] date NOT NULL, 
	[DURATION_HOURS] int NULL
);


GO
ALTER TABLE [Absence].[FACT_ABSENCE_TBL] ADD CONSTRAINT PK_FACT_ABSENCE_TBL primary key NONCLUSTERED ([TRANSACTION_NBR], [EMPLID_ID], [EMPL_RCD], [PIN_NUM], [BGN_DT], [END_DT]);
GO
ALTER TABLE [Absence].[FACT_ABSENCE_TBL] ADD CONSTRAINT FK_FACT_ABSENCE_TBL_DIM_PERSONAL_TBL FOREIGN KEY ([EMPLID_ID]) REFERENCES [Absence].[DIM_PERSONAL_TBL]([EMPLID_ID]);
GO
ALTER TABLE [Absence].[FACT_ABSENCE_TBL] ADD CONSTRAINT FK_FACT_ABSENCE_TBL_DIM_PIN_TBL FOREIGN KEY ([PIN_NUM]) REFERENCES [Absence].[DIM_PIN_TBL]([PIN_NUM]);